import type { CostCategoryDefinition, CostDefinition } from '@/types';

/**
 * Data-driven by design: adding a payment-provider preset or workspace hierarchy later
 * only means adding new registry/preset data, not new component code. Adding a new cost
 * or category here automatically wires up the field, checkbox, tooltip, default value,
 * category placement, persistence, visibility and calc participation.
 */
export const COST_CATEGORIES: CostCategoryDefinition[] = [
  { id: 'financial', label: 'Financeiro' },
  { id: 'operational', label: 'Operacional' },
];

export const COST_REGISTRY: CostDefinition[] = [
  {
    id: 'gatewayPercent',
    label: 'Gateway',
    description: 'Taxa percentual cobrada pelo processador de pagamentos.',
    category: 'financial',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'percent',
  },
  {
    id: 'gatewayFixedFee',
    label: 'Taxa Fixa do Gateway',
    description: 'Valor fixo cobrado pelo gateway por transação, além do percentual.',
    category: 'financial',
    type: 'money',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'money',
  },
  {
    id: 'checkoutPercent',
    label: 'Checkout',
    description: 'Taxa percentual cobrada pela plataforma de checkout.',
    category: 'financial',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'percent',
  },
  {
    id: 'iofPercent',
    label: 'IOF',
    description: 'Imposto sobre operações financeiras, aplicado em pagamentos internacionais.',
    category: 'financial',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'receipt',
  },
  {
    id: 'fxConversionPercent',
    label: 'Conversão Cambial',
    description: 'Spread cobrado pela conversão entre moedas.',
    category: 'financial',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'money',
  },
  {
    id: 'reservePercent',
    label: 'Reserva',
    description: 'Percentual reservado para chargebacks, reembolsos e perdas.',
    category: 'financial',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'shield',
  },
  {
    id: 'marketingPercent',
    label: 'Marketing',
    description: 'Percentual do preço de venda destinado a investimento em marketing.',
    category: 'operational',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'percent',
  },
  {
    id: 'taxPercent',
    label: 'Impostos',
    description: 'Percentual de impostos incidentes sobre a venda.',
    category: 'operational',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'receipt',
  },
  {
    id: 'extraPercent',
    label: 'Despesas Operacionais',
    description: 'Outras despesas operacionais do negócio, como percentual da venda.',
    category: 'operational',
    type: 'percent',
    defaultValue: 0,
    enabledByDefault: true,
    visibleByDefault: true,
    icon: 'percent',
  },
];
